adição criptografia de senhas
AndreWakugawa/DevMinds pull request #28
Opened 2023-05-27 18:57 UTC by avilajp

usei a biblioteca hashlib

2023-05-27 19:05 UTC, AndreWakugawa requested changes
A linha de teste de criptografia aparenta estar na mesma linha do usuário Cleber no usersDB, corrigir e colocar em outra linha seguindo o mesmo modelo dos outros users

2023-05-27 19:06 UTC, avilajp commented
acabei de verificar aqui, vou corrigir

2023-05-27 19:45 UTC, avilajp commented
Acabei de realizar um novo commit.

2023-05-27 19:47 UTC, avilajp commented
Além do que foi verificado pelo andre, estava ocorrendo o seguinte erro, a senha estava sendo criptografada dentro de user_edit_module.py, e sendo enviada para o usersDB.csv, entretanto, na hora de realizar o login de usuário, ocorria o seguinte erro, ele não aceitava a senha normal, só a senha criptografada, por causa do arquivo login_auth_module.py

2023-05-27 19:49 UTC, avilajp commented
ao constatar isso fiz uma nova verificação e atualização no código o que teve de ser feito foi inclui a lib hashlib dentro de login_auth_module.py, para que ao realizar o login ele sincronizasse a criptografia de senha do 'banco csv' com o login de usuário entretanto o que acontece é o seguinte, aparte deste commit o login só vai aceitar senhas que sejam criptografadas pelo cadastro, ou seja ele não aceita mais as senhas que não tem criptografia dentro de usersDB.csv, ou seja os usuários aaa@adm.com e user1@user.com que não tem senhas criptografadas, não podem realizar o login, pois não passam pela autenticação que eu criei

2023-05-27 19:50 UTC, avilajp commented
essa autenticação de login está na linha 17 de login_auth_module.py: if linha[3] == email and linha[4] == hashed_password_input: veja que adicionei o parametro hashed_password_input: onde anteriormente só tinha senha: essa mudança sicroniza a criptografia da senha e a compara no momento de cadastro, para o login e ja puxa do arquivo usersDB.csv

2023-05-27 19:51 UTC, avilajp commented
com isso vamos supor que cadastre email: joao@teste.com senha:111 depois disso dentro de usersDB.csv, voce vai ver a senha como: f6e0a1e2ac41945a9aa7ff8a8aaa0cebc12a3bcc981a929ad5cf810a090e11ae mas na hora de realizar o login é só colocar a senha: 111 que vai conseguir passar pela autenticação de criptografia facilmente

2023-05-27 19:58 UTC, AndreWakugawa approved these changes

2023-05-27 19:59 UTC, AndreWakugawa requested changes
O usuário Cleber deve ter o user_level definido como 0, o último commit mudou pra 03. O resto não consegui verificar porque estou no celular

2023-05-27 20:02 UTC, avilajp commented
Aah kkk eu devo ter colocado sem querer kkkkk

2023-05-27 20:03 UTC, avilajp commented
Pronto tirei o 3

2023-05-27 20:31 UTC, AndreWakugawa approved these changes

2023-05-29 20:03 UTC, AndreWakugawa commented
Podemos guardar o Merge desse PR pra depois que desenvolvermos as outras funções? Assim não teríamos problema de esquecer a senha do João adm e do Cleber user que estamos testando por enquanto

2023-06-03 21:42 UTC, closed without merging